- name: Setup WireGuard VPN
  hosts: all
  become: yes
  tasks:
    - name: Install WireGuard
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - resolvconf
        - wireguard

    - name: Add Peers to the wireguard network
      become: true
      ignore_errors: true
      ansible.builtin.shell: |
        sudo wg-quick down wg0
      args:
        executable: /bin/bash    

    - name: Generate WireGuard Private Keys
      command: wg genkey
      register: wg_private_key
      changed_when: false
      check_mode: false

    - name: Generate WireGuard Public Keys
      shell: "echo {{ wg_private_key.stdout }} | wg pubkey"
      register: wg_public_key
      changed_when: false
      check_mode: false

    - name: Display private key
      debug:
        msg: "The WireGuard private key is {{ wg_private_key.stdout }}"

    - name: Display public key
      debug:
        msg: "The WireGuard public key is {{ wg_public_key.stdout }}"  

    - name: Make sysctl changes permanent
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: "{{ item.line }}"
        create: yes
      with_items:
        - { line: 'net.ipv4.ip_forward=1' }
        - { line: 'net.ipv6.conf.all.forwarding=1' }

    - name: Set up WireGuard configuration
      template:
        src: templates/wg0.conf.j2
        dest: /etc/wireguard/wg0.conf
      # notify: restart wireguard

    - name: Enable and start WireGuard
      systemd:
        name: wg-quick@wg0
        enabled: yes
        state: restarted

    - name: Add Peers to the wireguard network
      become: true
      ansible.builtin.shell: |
        sudo wg set wg0 peer {{ hostvars['dev-challenger-01'].wg_public_key.stdout }} allowed-ips 10.8.0.1,10.8.0.100/32
        sudo wg set wg0 peer {{ hostvars['dev-challenger-02'].wg_public_key.stdout }} allowed-ips 10.8.0.2
      args:
        executable: /bin/bash
      when: inventory_hostname == 'dev-challenger-03'

  handlers:
    - name: restart wireguard
      systemd:
        name: wg-quick@wg0
        state: restarted

