---
- name: Set-up zkyoto
  hosts: nodes
  become: true
  gather_facts: true
  vars:
    yoto_dir: /etc/zkevm
    zkevm_net: testnet
    jwtsecret_key: "dea0ec10143704794fc53b845b783e302a7e3f8d480ebf9d0490fa41f7d92f14"
  roles:
    - ../roles/zkyoto