version: "3.5"
networks:
  default:
    name: zkevm
services:
  geth-go:
    container_name: geth-go
    restart: unless-stopped
    image: ethereum/client-go:stable
    command:
      - --sepolia
      - --datadir="/var/lib/goethereum"
      - --cache=2048 
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=eth,net,web3,admin,engine
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/config/jwtsecret
      - --http.corsdomain=*
      - --http.vhosts=*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.origins=*
      - --ws.api=txpool,admin,eth,net,web3,personal,engine
    ports:
      - "8544:8545"
      - "30303:30303"
      - "8551:8551"
    volumes:
      - ./secret/jwtsecret:/config/jwtsecret
      - /data/geth:/var/lib/goethereum

  lighthouse-beacon:
    container_name: lighthouse-beacon
    image: sigp/lighthouse
    command:
      - lighthouse 
      -  beacon_node
      - --network=sepolia
      - --http
      - --http-address=0.0.0.0
      - --execution-endpoint=http://geth-go:8551
      - --execution-jwt=/config/jwtsecret
      - --checkpoint-sync-url=https://sepolia.beaconstate.info
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "127.0.0.1:5052:5052"
    volumes:
      - ./secret/jwtsecret:/config/jwtsecret
    restart: unless-stopped      
  zkevm-rpc:
    container_name: zkevm-rpc
    restart: unless-stopped
    depends_on:
      zkevm-pool-db:
        condition: service_healthy
      zkevm-state-db:
        condition: service_healthy
      zkevm-sync:
        condition: service_started
      geth-go:
        condition: service_started
      lighthouse-beacon:
        condition: service_started
    image: staketechnologies/cdk-validium-node:0.5.13-cdk.4
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    ports:
      - 8545:8545
      - 9091:9091
    environment:
      - ZKEVM_NODE_ETHERMAN_URL=${ZKEVM_NODE_ETHERMAN_URL}
      - ZKEVM_NODE_ETHERMAN_PRIVATEKEYPATH=${ZKEVM_NODE_ETHERMAN_PRIVATEKEYPATH}
    volumes:
      - ${ZKEVM_ADVANCED_CONFIG_DIR:-./config/environments/${ZKEVM_NETWORK}}/node.config.toml:/app/config.toml
      - ${ZKEVM_ADVANCED_CONFIG_DIR:-./config/environments/${ZKEVM_NETWORK}}/zkyoto.genesis.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components rpc --http.api=eth,net,debug,zkevm,txpool,web3"

  zkevm-sync:
    container_name: zkevm-sync
    restart: unless-stopped
    depends_on:
      zkevm-state-db:
        condition: service_healthy
      geth-go:
        condition: service_started
      lighthouse-beacon:
        condition: service_started  
    image: staketechnologies/cdk-validium-node:0.5.13-cdk.4
    ports:
      - 9092:9091 # needed if metrics enabled
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    environment:
      - ZKEVM_NODE_ETHERMAN_URL=${ZKEVM_NODE_ETHERMAN_URL}
    volumes:
      - ${ZKEVM_ADVANCED_CONFIG_DIR:-./config/environments/${ZKEVM_NETWORK}}/node.config.toml:/app/config.toml
      - ${ZKEVM_ADVANCED_CONFIG_DIR:-./config/environments/${ZKEVM_NETWORK}}/zkyoto.genesis.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --network custom --custom-network-file /app/genesis.json --cfg /app/config.toml --components synchronizer"

  zkevm-state-db:
    container_name: zkevm-state-db
    restart: unless-stopped
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./db/init_prover_db.sql:/docker-entrypoint-initdb.d/init.sql
      - ${ZKEVM_NODE_STATEDB_DATA_DIR}:/var/lib/postgresql/data
      - ${ZKEVM_ADVANCED_CONFIG_DIR:-./config/environments/${ZKEVM_NETWORK}}/postgresql.conf:/etc/postgresql.conf
    environment:
      - POSTGRES_USER=prover_user
      - POSTGRES_PASSWORD=prover_pass
      - POSTGRES_DB=prover_db
    command:
      - "postgres"
      - "-N"
      - "500"
      - "-c"
      - "config_file=/etc/postgresql.conf"

  zkevm-pool-db:
    container_name: zkevm-pool-db
    restart: unless-stopped
    image: postgres:15
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5433:5432
    volumes:
      - ${ZKEVM_NODE_POOLDB_DATA_DIR}:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pool_user
      - POSTGRES_PASSWORD=pool_password
      - POSTGRES_DB=pool_db
    command:
      - "postgres"
      - "-N"
      - "500"

  zkevm-prover:
    container_name: zkevm-prover
    restart: unless-stopped
    image: staketechnologies/zkevm-prover:v4.0.19
    depends_on:
      zkevm-state-db:
        condition: service_healthy
    ports:
      - 50061:50061 # MT
      - 50071:50071 # Executor
    volumes:
      - ${ZKEVM_ADVANCED_CONFIG_DIR:-./config/environments/${ZKEVM_NETWORK}}/prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json
